"""Единый контракт событий Kafka.

Pydantic-модели — источник истины; JSON Schema для Schema Registry генерируется из них.
"""

from events.base import BaseEvent, ContractModel, schema_document
from events.ids import uuid7
from events.models import (
    ALL_EVENTS,
    EVENTS_BY_TOPIC,
    TOPICS,
    InventoryReleased,
    InventoryReleasedPayload,
    InventoryReservationFailed,
    InventoryReservationFailedPayload,
    InventoryReserved,
    InventoryReservedPayload,
    MissingItem,
    OrderCreated,
    OrderCreatedPayload,
    OrderItem,
    OrderStatusChanged,
    OrderStatusChangedPayload,
    ProductChanged,
    ProductChangedPayload,
    ReservedItem,
    UserCreated,
    UserCreatedPayload,
    UserRolesChanged,
    UserRolesChangedPayload,
    UserVerificationRequested,
    UserVerificationRequestedPayload,
    dlq_topic,
)
from events.serde import make_deserializer, make_serializer, subject_name
from events.types import (
    AuthProvider,
    Currency,
    Money,
    OrderStatus,
    ReleaseReason,
    ReservationFailureReason,
    Role,
    UtcDateTime,
)

__all__ = [
    "ALL_EVENTS",
    "EVENTS_BY_TOPIC",
    "TOPICS",
    "AuthProvider",
    "BaseEvent",
    "ContractModel",
    "Currency",
    "InventoryReleased",
    "InventoryReleasedPayload",
    "InventoryReservationFailed",
    "InventoryReservationFailedPayload",
    "InventoryReserved",
    "InventoryReservedPayload",
    "MissingItem",
    "Money",
    "OrderCreated",
    "OrderCreatedPayload",
    "OrderItem",
    "OrderStatus",
    "OrderStatusChanged",
    "OrderStatusChangedPayload",
    "ProductChanged",
    "ProductChangedPayload",
    "ReleaseReason",
    "ReservationFailureReason",
    "ReservedItem",
    "Role",
    "UserCreated",
    "UserCreatedPayload",
    "UserRolesChanged",
    "UserRolesChangedPayload",
    "UserVerificationRequested",
    "UserVerificationRequestedPayload",
    "UtcDateTime",
    "dlq_topic",
    "make_deserializer",
    "make_serializer",
    "schema_document",
    "subject_name",
    "uuid7",
]
