# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders_proto/catalog/v1/product.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orders_proto/catalog/v1/product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%orders_proto/catalog/v1/product.proto\x12\x11orders.catalog.v1\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\")\n\x12GetProductsRequest\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t\"C\n\x13GetProductsResponse\x12,\n\x08products\x18\x01 \x03(\x0b\x32\x1a.orders.catalog.v1.Product\"\xf3\x01\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\t\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\x12\x14\n\x0cis_published\x18\x08 \x01(\x08\x12\x0f\n\x07version\x18\t \x01(\x03\x12\x0e\n\x06images\x18\n \x03(\t\x12\x17\n\x0f\x61ttributes_json\x18\x0b \x01(\t\x12\x12\n\ncreated_at\x18\x0c \x01(\t\x12\x12\n\nupdated_at\x18\r \x01(\t2\xbe\x01\n\x0eProductService\x12N\n\nGetProduct\x12$.orders.catalog.v1.GetProductRequest\x1a\x1a.orders.catalog.v1.Product\x12\\\n\x0bGetProducts\x12%.orders.catalog.v1.GetProductsRequest\x1a&.orders.catalog.v1.GetProductsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_proto.catalog.v1.product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPRODUCTREQUEST']._serialized_start=60
  _globals['_GETPRODUCTREQUEST']._serialized_end=99
  _globals['_GETPRODUCTSREQUEST']._serialized_start=101
  _globals['_GETPRODUCTSREQUEST']._serialized_end=142
  _globals['_GETPRODUCTSRESPONSE']._serialized_start=144
  _globals['_GETPRODUCTSRESPONSE']._serialized_end=211
  _globals['_PRODUCT']._serialized_start=214
  _globals['_PRODUCT']._serialized_end=457
  _globals['_PRODUCTSERVICE']._serialized_start=460
  _globals['_PRODUCTSERVICE']._serialized_end=650
# @@protoc_insertion_point(module_scope)
