# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from orders_proto.catalog.v1 import product_pb2 as orders__proto_dot_catalog_dot_v1_dot_product__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orders_proto/catalog/v1/product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/orders.catalog.v1.ProductService/GetProduct',
                request_serializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductRequest.SerializeToString,
                response_deserializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.Product.FromString,
                _registered_method=True)
        self.GetProducts = channel.unary_unary(
                '/orders.catalog.v1.ProductService/GetProducts',
                request_serializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductsRequest.SerializeToString,
                response_deserializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductsResponse.FromString,
                _registered_method=True)


class ProductServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetProduct(self, request, context):
        """Товар по id. NOT_FOUND, если товара нет или он удалён.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducts(self, request, context):
        """Товары по списку id (не более 100). Неизвестные id пропускаются.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductRequest.FromString,
                    response_serializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.Product.SerializeToString,
            ),
            'GetProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducts,
                    request_deserializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductsRequest.FromString,
                    response_serializer=orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.catalog.v1.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orders.catalog.v1.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.catalog.v1.ProductService/GetProduct',
            orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductRequest.SerializeToString,
            orders__proto_dot_catalog_dot_v1_dot_product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.catalog.v1.ProductService/GetProducts',
            orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductsRequest.SerializeToString,
            orders__proto_dot_catalog_dot_v1_dot_product__pb2.GetProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
