# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from orders_proto.inventory.v1 import inventory_pb2 as orders__proto_dot_inventory_dot_v1_dot_inventory__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orders_proto/inventory/v1/inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAvailability = channel.unary_unary(
                '/orders.inventory.v1.InventoryService/CheckAvailability',
                request_serializer=orders__proto_dot_inventory_dot_v1_dot_inventory__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=orders__proto_dot_inventory_dot_v1_dot_inventory__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckAvailability(self, request, context):
        """Проверка наличия без резервирования (быстрый отказ при оформлении заказа).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=orders__proto_dot_inventory_dot_v1_dot_inventory__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=orders__proto_dot_inventory_dot_v1_dot_inventory__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orders.inventory.v1.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orders.inventory.v1.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orders.inventory.v1.InventoryService/CheckAvailability',
            orders__proto_dot_inventory_dot_v1_dot_inventory__pb2.CheckAvailabilityRequest.SerializeToString,
            orders__proto_dot_inventory_dot_v1_dot_inventory__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
