# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders_proto/inventory/v1/inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'orders_proto/inventory/v1/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)orders_proto/inventory/v1/inventory.proto\x12\x13orders.inventory.v1\",\n\x04Item\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"D\n\x18\x43heckAvailabilityRequest\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.orders.inventory.v1.Item\"L\n\x10ItemAvailability\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x11\n\trequested\x18\x02 \x01(\x05\x12\x11\n\tavailable\x18\x03 \x01(\x05\"d\n\x19\x43heckAvailabilityResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x34\n\x05items\x18\x02 \x03(\x0b\x32%.orders.inventory.v1.ItemAvailability2\x86\x01\n\x10InventoryService\x12r\n\x11\x43heckAvailability\x12-.orders.inventory.v1.CheckAvailabilityRequest\x1a..orders.inventory.v1.CheckAvailabilityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_proto.inventory.v1.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=66
  _globals['_ITEM']._serialized_end=110
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_start=112
  _globals['_CHECKAVAILABILITYREQUEST']._serialized_end=180
  _globals['_ITEMAVAILABILITY']._serialized_start=182
  _globals['_ITEMAVAILABILITY']._serialized_end=258
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_start=260
  _globals['_CHECKAVAILABILITYRESPONSE']._serialized_end=360
  _globals['_INVENTORYSERVICE']._serialized_start=363
  _globals['_INVENTORYSERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
